openapi: 3.1.0
info:
  title: Payroc API
  version: '1'
paths: {}

components:    
  parameters:
    fundingAccountId:
      name: fundingAccountId
      in: path
      required: true
      description: Unique identifier of the funding account. 
      schema:
        type: integer
      examples:
        example:
          value: 123
