openapi: 3.1.0

paths: {}

info:
  title: Common Domain Models
  description: Common domain models that are shared across the Payroc Universal API
  version: '1'
  contact:
    name: Payroc Helpdesk
    url: https://www.payroc.com/help
    email: helpdesk@payroc.com

tags:
  - name: Common schemas
    description: Common schemas that can be resued

components:
  schemas:
    cardSummary:
      type: object
      title: card summary
      description: Object that contains information about the card.
      properties:
        cardNumber:
          type: string
          description: Masked card number. Our gateway shows only the first six digits and the last four digits of the card number, for example, `500165******0000`.
          example: 453985******7062
        type:
          type: [string, 'null']
          description: | 
            Card type, for example, Visa.  

            **Note:** If we can’t match a dispute to a transaction, we don’t return a type object. 
          enum:
            - visa 
            - masterCard
            - discover
            - debit
            - ebt 
            - wrightExpress
            - voyager
            - amex
            - privateLabel
            - storedValue
            - discoverRetained
            - jcbNonSettled
            - dinersClub
            - amexOptBlue
            - fuelman
            - unknown
        cvvPresenceIndicator:
          type: boolean
          description: Indicates whether the cardholder provided the Card Verification Value (CVV). 
        avsRequest:
          type: boolean
          description: Indicates whether the merchant used the Address Verification Service (AVS) to verify the cardholder's address.  
        avsResponse:
          type: string
          description: Response from the Address Verification Service (AVS).
