openapi: 3.1.0

paths: {}

info:
  title: Common Domain Models
  description: Common domain models that are shared across the Payroc Universal API
  version: '1'
  contact:
    name: Payroc Helpdesk
    url: https://www.payroc.com/help
    email: helpdesk@payroc.com

tags:
  - name: Common schemas
    description: Common schemas that can be resued

components:
  schemas:
    merchantSummary:
      type: object
      title: merchant summary
      description: Object that contains information about the merchant.
      properties:
        merchantId:
          type: string
          description: Unique identifier that the processor assigned to the merchant. 
          example: '4525644354'
        doingBusinessAs:
          type: string
          description: Trading name of the business.
          example: Pizza Doe
        processingAccountId:
            type: string
            description: Unique identifier that we assigned to the processing account.
            example: '38765'
        link:
          $ref: '../common/link/link-v1.yaml#/components/schemas/link'
      example:
        merchantId: '4525644354'
        doingBusinessAs: Pizza Doe
        processingAccountId: '38765'
        link: 
          rel: processingAccount
          method: get
          href: 'https://api.payroc.com/v1/processing-accounts/38765'