openapi: 3.1.0
info:
  title: Payroc API
  version: '1'
paths: {}

components:
  examples:
    refundInstructionRequest:
      summary: Refund instruction
      description: Submit an instruction for initiating a refund on a physical device.
      value:
        operator: Jane
        processingTerminalId: '1234001'
        order:
          orderId: OrderRef6543
          currency: USD
          amount: 4999
          description: Refund for order OrderRef6543
        customizationOptions:
          entryMethod: manualEntry
