openapi: 3.0.3
info:
  title: Payroc API
  version: '1'
paths: {}

components:
  examples:
    refundInstruction:
      summary: Refund instruction
      description: Object that contains information about the progress of the refund instruction.
      value:
        refundInstructionId: a37439165d134678a9100ebba3b29597
        status: completed
        link:
          rel: refund
          method: GET
          href: https://api.payroc.com/v1/refunds/CD3HN88U9F

    refundInstructionInProgress:
      summary: Refund instruction
      description: Object that contains information about the progress of the refund instruction.
      value:
        refundInstructionId: a37439165d134678a9100ebba3b29597
        status: inProgress
        link:
          rel: self
          method: GET
          href: https://api.payroc.com/v1/refund-instructions/a37439165d134678a9100ebba3b29597
    refundInstructionCompleted:
      summary: Refund instruction already completed
      description: Refund instruction already completed
      value:
        type: https://docs.payroc.com/api/errors#cannot-be-deleted
        title: Cannot be deleted
        status: 409
        detail: "You cannot delete this resource in its current state"
        errors:
        - parameter: refundInstructionId
          message: Completed instruction cannot be deleted
        link:
          rel: refund
          method: GET
          href: https://api.payroc.com/v1/refunds/M2MJOG6O2Y  
    refundInstructionFailed:
      summary: Refund instruction failed
      description: Refund instruction failed
      value:
        type: https://docs.payroc.com/api/errors#cannot-be-deleted
        title: Cannot be deleted
        status: 409
        detail: "You cannot delete this resource in its current state"
        errors:
        - parameter: refundInstructionId
          message: Failed instruction cannot be deleted