openapi: 3.1.0
info:
  title: Payroc API
  version: '1'
paths: {}

components:             
  parameters:
    refundInstructionId:
      name: refundInstructionId
      description: Unique identifier of the refund instruction.
      in: path
      required: true
      schema:
        maxLength: 36
        minLength: 1
        type: string
      examples:
        example:
          value: a37439165d134678a9100ebba3b29597

    serialNumber:
      name: serialNumber
      description: Serial number that identifies the merchant’s payment device.
      in: path
      required: true
      schema:
        maxLength: 64
        minLength: 1
        type: string
      examples:
        example:
          value: '1850010868'
