openapi: 3.1.0
info:
  title: Payroc API
  version: '1'
paths: {}

components:
  parameters:
    eventId:
      name: eventId
      in: path
      description: Event Identifier
      required: true
      schema:
        type: string
        format: uuid
      examples:
        example:
          value: 'd9cc067f-af3e-4291-8390-9bd31f59a998'
