openapi: 3.1.0
info:
  title: Payroc API
  version: '1'
paths: {}

components:
  parameters:
    status:
      name: status
      in: query
      description: Filter event subscriptions by subscription status. 
      schema:
        type: string
        enum: [registered, suspended, failed]
      examples:
        example:
          value: registered

    event:
      name: event
      in: query
      description: Filter event subscriptions by an event type. For a list of event types, go to [Events List](https://docs.payroc.com/knowledge/events/events-list).   
      schema:
        type: string
      examples:
        example:
          value: processingAccount.status.changed

    subscriptionId:
      name: subscriptionId
      in: path
      description: Unique identifier that we assigned to the event subscription.
      required: true
      schema:
        type: integer
        format: int32
      examples:
        example:
          value: 7654

    from:
      name: from
      in: query
      description: Filters the events to only those that have occurred since `from`
      schema:
        type: string
        format: date-time

    to:
      name: to
      in: query
      description: Filters the events to only those that have occurred before `to`
      schema:
        type: string
        format: date-time

    notifiedStatus:
      name: status
      in: query
      description: Filters the events to only those that have a `notified status` matching the specified `status`
      schema:
        type: string
        enum: [success, failed, pending]
      examples:
        example:
          value: success
