openapi: 3.1.0
info:
  title: Settlement
  description: Settlement
  version: '1'
  termsOfService: https://www.payroc.com/terms
  contact:
    name: Payroc Helpdesk
    url: https://www.payroc.com/help
    email: helpdesk@payroc.com
security:
- bearerAuth: []
tags:
  - name: Settlement
    description: Settlement information.

paths: {}

components:
  securitySchemes:
    bearerAuth:
      type: http
      description: 'Example: Authorization: Bearer <token>'
      scheme: bearer
      bearerFormat: JWT
