openapi: 3.1.0
info:
  title: Payroc API
  version: '1'
paths: {}

components:             
  parameters:
    customerName:
      name: customerName
      in: query
      description: Filter by the customer's name.
      schema:
        maxLength: 50
        minLength: 1
        type: string
      examples:
        example:
          value: Sarah%20Hazel%20Hopper

    last4:
      name: last4
      in: query
      description: Filter by the last four digits of the card or account number.
      schema:
        pattern: "[0-9]{4}"
        type: string
      examples:
        example:
          value: '7062'

    paymentPlan:
      name: paymentPlan
      in: query
      description: Filter by the name of the payment plan.
      schema:
        maxLength: 128
        minLength: 1
        type: string
      examples:
        example:
          value: Premium%20Club

    frequency:
      name: frequency
      in: query
      description: Filter by the frequency of subscription payments.
      schema:
        type: string
        enum:
          - weekly
          - fortnightly
          - monthly
          - quarterly
          - yearly
      examples:
        example:
          value: monthly

    status:
      name: status
      in: query
      description: Filter by the current status of the subscription.
      schema:
        type: string
        enum:
          - active
          - completed
          - suspended
          - cancelled
      examples:
        example:
          value: active

    endDate:
      name: endDate
      in: query
      description: |
        Format: `YYYY-MM-DD`  
        Filter subscriptions that end on a specific date.
      schema:
        type: string
        format: date
      examples:
        example:
          value: '2025-07-01'
      
    nextDueDate:
      name: nextDueDate
      in: query
      description: |
        Format: `YYYY-MM-DD`  
        Filter subscriptions by the date that the next payment is collected.
      schema:
        type: string
        format: date
      examples:
        example:
          value: '2024-08-01'

    subscriptionId:
      name: subscriptionId
      in: path
      description: Unique identifier that the merchant assigned to the subscription.
      required: true
      schema:
        maxLength: 48
        minLength: 1
        type: string
      examples:
        example:
          value: SubRef7654
