openapi: 3.1.0
info:
  title: Payroc API
  version: '1'
paths: {}

components:
  parameters:
    authorizationId:
      name: authorizationId
      description: Unique identifier of the authorization.
      in: path
      required: true
      schema:
        type: integer
      examples:
        example:
          value: 12345
