openapi: 3.1.0
info:
  title: Payroc API
  version: '1'
paths: {}

components:
  parameters:
    ownerId:
      name: ownerId
      in: path
      description: Unique identifier that we assigned to the owner.
      required: true
      schema:
        type: integer
      examples:
        example:
          value: 4564
