openapi: 3.1.0

info:
  title: Common Domain Models
  description: Common domain models that are shared across the Payroc API
  version: '1'
  contact:
    name: Payroc Helpdesk
    url: https://www.payroc.com/help
    email: helpdesk@payroc.com

paths: {}

tags:
  - name: Common headers
    description: Common headers that can be reused

components:
  headers:
    CorrelationIdHeader:
      description: Unique identifier assigned for each request by the client.
      schema:
        type: string
        format: uuid
