openapi: 3.1.0
info:
  title: Payroc API
  version: '1'
paths: {}

components:
  parameters:
    terminalOrderId:
      name: terminalOrderId
      in: path
      description: Unique identifier of the terminal order.
      required: true
      schema:
        type: string
      examples:
        example:
          value: '12345'
