openapi: 3.1.0
info:
  title: Terminal orders
  description: Retrieve terminal orders
  version: '1'
  termsOfService: https://www.payroc.com/terms
  contact:
    name: Payroc Helpdesk
    url: https://www.payroc.com/help
    email: helpdesk@payroc.com
security:
- bearerAuth: []

tags:
  - name: Terminal orders
    description: Retrieve existing terminal orders

paths:
  /terminal-orders/{terminalOrderId}:
    get:
      tags:
      - Terminal orders
      summary: Retrieve terminal order
      description: |
        Use this method to retrieve information about a terminal order.  

        To retrieve a terminal order, you need it's terminalOrderId. Our gateway returned the terminalOrderId in the response of the [Create Terminal Order](https://docs.payroc.com/api/schema/boarding/processing-accounts/create-terminal-order) method.  

        **Note**: If you don't have the terminalOrderId, use our [List Terminal Orders](https://docs.payroc.com/api/schema/boarding/processing-accounts/list-terminal-orders) method to search for the terminal order.  

        Our gateway returns the following information about the terminal order:  
        - Status of the order  
        - Items in the order  
        - Training provider  
        - Shipping information  

        **Note**: You can subscribe to our terminalOrder.status.changed event to get notifications when we update the status of a terminal order. For more information about how to subscribe to events, go to [Events Subscriptions](https://docs.payroc.com/guides/integrate/event-subscriptions).  

      operationId: getTerminalOrder
      parameters:
      - $ref: './parameters-v1.yaml#/components/parameters/terminalOrderId'
      responses:
        200:
          description: Successful request. Returns the terminal order.
          content:
            application/json:
              schema:
                $ref: '../../../common/schemas/boarding/terminal-orders-v1.yaml#/components/schemas/terminalOrder'
              examples:
                terminalOrder:
                  $ref: './example-responses-v1.yaml#/components/examples/terminalOrder'
        400:
          $ref: '../../../common/responses/errors/400-v1.yaml#/components/responses/400'
        401:
          $ref: '../../../common/responses/errors/401-v1.yaml#/components/responses/401'
        403:
          $ref: '../../../common/responses/errors/403-v1.yaml#/components/responses/403'
        404:
          $ref: '../../../common/responses/errors/404-v1.yaml#/components/responses/404'
        406:
          $ref: '../../../common/responses/errors/406-v1.yaml#/components/responses/406'
        500:
          $ref: '../../../common/responses/errors/500-v1.yaml#/components/responses/500'
  
components:
  securitySchemes:
    bearerAuth:
      $ref: '../../../common/security/bearer-auth.yaml#/components/securitySchemes/bearerAuth'

