openapi: 3.0.3
info:
  title: Payroc API
  version: '1'
paths: {}

components:
  parameters:
    bankTransferPaymentsProcessingTerminalId:
      name: processingTerminalId
      in: query
      required: true
      description: Filter results by the unique identifier that we assigned to the terminal.
      schema:
        maxLength: 50
        minLength: 4
        type: string
      example: '1234001'

    bankTransferPaymentsOrderId:
      name: orderId
      in: query
      description: Filter results by the order ID of the payment. 
      schema:
        maxLength: 24
        minLength: 1
        type: string
      example: OrderRef6543

    bankTransferPaymentsNameOnAccount:
      name: nameOnAccount
      in: query
      description: Filter results by the account holder's name. 
      schema:
        maxLength: 50
        minLength: 1
        type: string
      example: Sarah%20Hazel%20Hopper

    bankTransferPaymentsLast4:
      name: last4
      in: query
      description: Filter results by the last four digits of the account number.
      schema:
        pattern: '[0-9]{4}'
        type: string
      example: '7890'

    bankTransferPaymentsType:
      name: type
      in: query
      description: Filter results by transaction type.
      schema:
        type: array
        items:
          type: string
          enum:
            - payment
            - accountVerification
      example:
        - payment

    bankTransferPaymentsStatus:
      name: status
      in: query
      description: Filter results by the status of the payment.
      schema:
        type: array
        items:
          type: string
          enum:
            - ready
            - pending
            - declined
            - complete
            - admin
            - reversal
            - returned
      example:
        - ready

    bankTransferPaymentsDateFrom:
      name: dateFrom
      in: query
      description: Filter results by payments that the merchant ran after a specific date. The value follows the [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) standard.
      schema:
        type: string
        format: date-time
      example: '2024-07-01T00:00:00Z'

    bankTransferPaymentsDateTo:
      name: dateTo
      in: query
      description: Filter results by payments that the merchant ran before a specific date. The value follows the [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) standard.
      schema:
        type: string
        format: date-time
      example: '2024-07-31T23:59:59Z'

    bankTransferPaymentsSettlementState:
      name: settlementState
      in: query
      description: Filter results by the settlement status.
      schema:
        type: string
        enum:
          - settled
          - unsettled
      example: settled

    bankTransferPaymentsSettlementDate:
      name: settlementDate
      in: query
      description: Filter results by the settlement date. Send a value in **YYYY-MM-DD** format. 
      schema:
        type: string
        format: date
      example: '2024-07-15'

    bankTransferPaymentsPaymentId:
      name: paymentId
      description: Unique identifier that our gateway assigned to the payment.
      in: path
      required: true
      schema:
        maxLength: 10
        minLength: 10
        type: string
      example: M2MJOG6O2Y

    paymentLinkId:
      name: paymentLinkId
      in: query
      description: Filter results by the paymentLinkId. 
      schema:
        maxLength: 10
        minLength: 10
        type: string
        example: JZURRJBUPS
