openapi: 3.1.0
info:
  title: Payroc API
  version: '1'
paths: {}

components:
  parameters:
    pricingIntentId:
      in: path
      name: pricingIntentId
      required: true
      description: Unique identifier that we assigned to the pricing intent.
      schema:
        type: string
      examples:
        example:
          value: '5'
