openapi: 3.1.0
info:
  title: Payroc API
  version: '1'
paths: {}

components:
  parameters:
    transactionId:
      name: transactionId
      description: Unique identifier of the transaction.
      in: path
      required: true
      schema:
        type: integer
      examples:
        example:
          value: 442233

    transactionType:
      name: transactionType
      in: query
      description: Type of transaction.
      schema:
        type: string
        enum:
          - Capture
          - Return
      examples:
        example:
          value: Capture
