openapi: 3.1.0

info:
  title: Common Domain Models
  description: Common domain models that are shared across the Payroc API
  version: '1'
  contact:
    name: Payroc Helpdesk
    url: https://www.payroc.com/help
    email: helpdesk@payroc.com

paths: {}

tags:
  - name: Common parameters
    description: Common parameters that can be reused

components:
  parameters:
    before:
      name: before
      in: query
      description: |
        Return the previous page of results before the value that you specify.  

        You can’t send a before parameter in the same request as an after parameter. 
      schema:
        type: string
      examples:
        example:
          value: '2571'
