openapi: 3.1.0

info:
  title: Common Domain Models
  description: Common domain models that are shared across the Payroc API
  version: '1'
  contact:
    name: Payroc Helpdesk
    url: https://www.payroc.com/help
    email: helpdesk@payroc.com

paths: {}

tags:
  - name: Common parameters
    description: Common parameters that can be reused

components:
  parameters:
    idempotencyKey:
      name: Idempotency-Key
      in: header
      required: true
      description: Unique identifier that you generate for each request. You must use the [UUID v4 format](https://www.rfc-editor.org/rfc/rfc4122) for the identifier. For more information about the idempotency key, go to [Idempotency](https://docs.payroc.com/api/idempotency).
      schema:
        type: string
        format: uuid
      examples:
        example:
          value: '8e03978e-40d5-43e8-bc93-6894a57f9324'
