openapi: 3.1.0

info:
  title: Common Domain Models
  description: Common domain models that are shared across the Payroc API
  version: '1'
  contact:
    name: Payroc Helpdesk
    url: https://www.payroc.com/help
    email: helpdesk@payroc.com

paths: {}

tags:
  - name: Common parameters
    description: Common parameters that can be reused

components:
  parameters:
    limit:
      name: limit
      in: query
      description: States the total amount of results the response is limited to.
      schema:
        type: integer
        default: 10
        maximum: 100
      examples:
        example:
          value: 25
