openapi: 3.1.0
info:
  title: Payroc API
  version: '1'

paths: {}

components:
  parameters:
    processingTerminalIdPath:
      name: processingTerminalId
      in: path
      required: true
      description: Unique identifier that we assigned to the terminal.
      schema:
        maxLength: 50
        minLength: 4
        type: string
      examples:
        example:
          value: '1234001'

    processingTerminalIdQuery:
      name: processingTerminalId
      in: query
      description: Filter by terminal ID.
      schema:
        maxLength: 50
        minLength: 4
        type: string
      examples:
        example:
          value: '1234001'
