openapi: 3.1.0

info:
  title: Common Domain Models
  description: Common domain models that are shared across the Payroc API
  version: '1'
  contact:
    name: Payroc Helpdesk
    url: https://www.payroc.com/help
    email: helpdesk@payroc.com

paths: {}

tags:
  - name: Common parameters
    description: Common parameters that can be reused

components:
  parameters:
    batchId:
      name: batchId
      in: path
      required: true
      description: Unique identifier that we assigned to the batch.
      style: simple
      schema:
        type: integer
      examples:
        example:
          value: 12345

    batchIdQuery:
      name: batchId
      in: query
      required: true
      description: Unique identifier of the batch. You must provide either the 'batchId' or the 'date'.
      schema:
        type: integer
      examples:
        example:
          value: 12345

    keyDate:
      name: date
      in: query
      required: true
      description: Date to retrieve results from. The format of this value is **YYYY-MM-DD**. You must provide either the 'batchId' or the 'date'.
      schema:
        type: string
        format: date
      examples:
        example:
          value: '2024-07-01'
