openapi: 3.1.0
info:
  title: Payroc API
  version: '1'
paths: {}

components:
  parameters:
    binNumber:
      name: binNumber
      in: path
      description: Card's BIN.
      required: true
      schema:
        type: string
      examples:
        example:
          value: '123456789012'

    dateTime:
      in: query
      name: dateTime
      description: Retrieve BIN information for a specific date. 
      schema:
        type: string
      examples:
        example:
          value: '2024-07-02T15:30:00Z'
