openapi: 3.1.0

paths: {}

info:
  title: Common Domain Models
  description: Common domain models that are shared across the Payroc API
  version: '1'
  contact:
    name: Payroc Helpdesk
    url: https://www.payroc.com/help
    email: helpdesk@payroc.com

tags:
  - name: Common schemas
    description: Common schemas that can be resued

components:
  schemas:
    fundingAccountSummary:
      type: object
      title: funding account summary
      properties:
        fundingAccountId:
          description: Unique identifier that we assigned to the funding account. 
          type: integer
          readOnly: true
          example: 123
        status:
          description: Status of the funding account. 
          type: string
          readOnly: true
          example: pending
          enum:
          - approved
          - rejected
          - pending
        link:
          description: Object that contains HATEOAS links for the funding accounts that are linked to the processing account. 
          readOnly: true
          $ref: '../common/link/link-v1.yaml#/components/schemas/link'
