openapi: 3.1.0
info:
  title: Payroc API
  version: '1'
paths: {}

components:
  parameters:
    processingAccountId:
      name: processingAccountId
      in: path
      description: Unique identifier of the processing account.
      required: true
      schema:
        type: string
      examples:
        example:
          value: '38765'
