openapi: 3.1.0
info:
  title: Payroc API
  version: '1'
paths: {}

components:
  parameters:
    contactId:
      name: contactId
      in: path
      description: Unique identifier for the contact.
      required: true
      schema:
        type: integer
      examples:
        example:
          value: 1543
