openapi: 3.1.0
info:
  title: Payroc API
  version: '1'
paths: {}

components:
  parameters:
    recipientId:
      name: recipientId
      description: Unique identifier of the funding recipient.
      in: path
      required: true
      schema:
        type: integer
      example: 234
