openapi: 3.1.0

paths: {}

info:
  title: Common Domain Models
  description: Common domain models that are shared across the Payroc API
  version: '1'
  contact:
    name: Payroc Helpdesk
    url: https://www.payroc.com/help
    email: helpdesk@payroc.com

tags:
  - name: Common schemas
    description: Common schemas that can be resued

components:
  schemas:
    address:
      required:
      - city
      - country
      - address1
      - postalCode
      - state
      type: object
      title: address
      description: Object that contains information about the address.
      properties:
        address1:
          type: string
          description: Address line 1.
          example: 1 Example Ave.
          maxLength: 150
        address2:
          type: string
          description: Address line 2.
          example: Example Address Line 2
          maxLength: 150
        address3:
          type: string
          description: Address line 3.
          example:  Example Address Line 3
          maxLength: 150
        city:
          type: string
          description: City.
          example: Chicago
          maxLength: 50
        state:
          type: string
          description: Name of the state or state abbreviation.
          example: Illinois
          maxLength: 50
        country:
          maxLength: 2
          minLength: 2
          type: string
          description: Two-digit country code for the country that the business operates in. The format follows the [ISO-3166-1](https://www.iso.org/iso-3166-country-codes.html) standard.
          example: US
        postalCode:
          type: string
          description: Zip code or postal code.
          example: '60056'
          maxLength: 10
