openapi: 3.1.0
info:
  title: Payroc API
  version: '1'
paths: {}

components:
  parameters:
    date:
      name: date
      in: query
      required: true
      description: Filter batches by the date that they were submitted. The format of this value is **YYYY-MM-DD**.
      schema:
        type: string
        format: date
      examples:
        example:
          value: '2027-07-02'
