openapi: 3.1.0
info:
  title: Payroc API
  version: '1'
paths: {}

components: 
  parameters:
    achDepositId:
      name: achDepositId
      description: Unique identifier of the ACH deposit.
      in: path
      required: true
      schema:
        type: integer
      examples:
        example:
          value: 99

    achDepositIdQuery:
      name: achDepositId
      description: Unique identifier of the ACH deposit. You must provide either the 'achDepositId' or the 'date'.
      in: query
      required: true
      schema:
        type: integer
      examples:
        example:
          value: 99

  securitySchemes:
    bearerAuth:
      $ref: '../../../common/security/bearer-auth.yaml#/components/securitySchemes/bearerAuth'
