openapi: 3.1.0
info:
  title: Payroc API
  version: '1'
paths: {}

components:             
  parameters:
    merchantPlatformId:
      name: merchantPlatformId
      in: path
      description: Unique identifier of the merchant platform that we sent to you when you created the merchant platform.
      required: true
      schema:
        type: string
      examples:
        example:
          value: '12345'

    includeClosed:
      name: includeClosed
      in: query          
      description: |
        Indicates if you want to return closed processing accounts. This includes processing accounts that have a status of `terminated`, `cancelled`, or `rejected`.  
        **Note**: By default, we return only open processing accounts.  
      schema:
        type: boolean
        default: false
      examples:
        example:
          value: false
