openapi: 3.1.0
info:
  title: Payroc API
  version: '1'
paths: {}

components:
  examples:
    createSessionRequest:
      summary: Create session request
      description: Create session request.
      value:
        libVersion: '1.1.0.123456'
        scenario: payment