openapi: 3.1.0
info:
  title: Payroc API
  version: '1'
paths: {}

components:             
  parameters:
    paymentInstructionId:
      name: paymentInstructionId
      description: Unique identifier that we assigned to the payment instruction. 
      in: path
      required: true
      schema:
        maxLength: 36
        minLength: 1
        type: string
      examples:
        example:
          value: 'e743a9165d134678a9100ebba3b29597'

    serialNumber:
      name: serialNumber
      description: Serial number that identifies the merchant’s payment device.
      in: path
      required: true
      schema:
        maxLength: 64
        minLength: 1
        type: string
      examples:
        example:
          value: '1850010868'
