openapi: 3.1.0
info:
  title: Payroc API
  version: '1'
paths: {}

components:             
  parameters:
    paymentPlanId:
      name: paymentPlanId
      in: path
      description: Unique identifier that the merchant assigned to the payment plan.
      required: true
      schema:
        maxLength: 48
        minLength: 1
        type: string
      examples:
        example:
          value: PlanRef8765
