openapi: 3.1.0
info:
  title: Payroc API
  version: '1'
paths: {}

components:
  examples:
    bankAccountVerificationResponse:
      summary: Bank Account Verification Response
      description: Bank Account Verification Response
      value:
        processingTerminalId: '1234001'
        verified: true
