openapi: 3.0.3

paths: {}

info:
  title: Common Domain Models
  description: Common domain models that are shared across the Payroc API
  version: '1'
  contact:
    name: Payroc Helpdesk
    url: https://www.payroc.com/help
    email: helpdesk@payroc.com

tags:
  - name: Common schemas
    description: Common schemas that can be resued

components:
  schemas:
    link:
      type: object
      readOnly: true
      description: Object that contains HATEOAS links for the resource. 
      properties:
        rel:
          type: string
          description: Indicates the relationship between the current resource and the target resource. 
        method:
          type: string
          description: HTTP method that you need to use with the target resource. 
        href:
          type: string
          description: URL of the target resource. 
      required:
      - href
      - method
      - rel
      example:
        rel: "previous"
        method: "get"
        href: "<uri>"
