openapi: 3.1.0
info:
  title: Payroc API
  version: '1'
paths: {}

components:
  examples:
    singleUseTokenRequest:
      summary: Create single-use token 
      description: Create a single-use token. The token expires after 30 minutes. 
      value:
        channel: web
        operator: Jane
        source:
          type: card
          cardDetails:
            entryMethod: keyed
            cardholderName: Sarah Hazel Hopper
            keyedData:
              dataFormat: plainText
              cardNumber: '4539858876047062'
              expiryDate: '1225'
              cvv: '234'
