openapi: 3.1.0
info:
  title: Payroc API
  version: '1'
paths: {}

components:             
  parameters:    
    processingTerminalId:
      name: processingTerminalId
      in: path
      required: true
      description: Unique identifier that our gateway assigned to the terminal.
      schema:
        maxLength: 50
        minLength: 4
        type: string
      examples:
        example:
          value: '1234001'
