openapi: 3.1.0
info:
  title: Payroc API
  version: '1'
paths: {}

components: 
  parameters:
    disputeId:
      name: disputeId
      description: Unique identifier of the dispute.
      in: path
      required: true
      schema:
        type: integer
      examples:
        example:
          value: 12345

    date:
      name: date
      in: query
      required: true
      description: Filter results by the date that the dispute was submitted.
      schema:
        type: string
        format: date
      examples:
        example:
          value: '2024-07-02'

  securitySchemes:
    bearerAuth:
      $ref: '../../../common/security/bearer-auth.yaml#/components/securitySchemes/bearerAuth'
