openapi: 3.1.0
info:
  title: Payroc API
  version: '1'
paths: {}

components: 
  parameters:
    instructionId:
      name: instructionId
      in: path
      required: true
      description: Unique identifier of the funding instruction.
      schema:
        type: integer
      examples:
        example:
          value: 64643131

    dateFrom:
      name: dateFrom
      in: query
      description: Retrieve activity that occured since `dateFrom`. We can return activity from only the last two years.
      required: true
      schema:
        type: string
        format: date
      examples:
        example:
          value: '2024-07-01'

    dateTo:
      name: dateTo
      in: query
      required: true
      description: Retrieve activity that occured before `dateTo`.
      schema:
        type: string
        format: date
      examples:
        example:
          value: '2024-07-03'
